# src/app_api.py
from fastapi import FastAPI
import pandas as pd
import glob
import os

app = FastAPI(title="IoT Pipeline API")

DATA_DIR = "data/output_live"

@app.get("/")
def home():
    return {"status": "API is online", "endpoint": "/api/metrics"}

@app.get("/api/metrics")
def get_metrics():
    """Reads the latest JSON outputs generated by the Spark Stream"""
    try:
        # Find all JSON files generated by Spark in the output directory
        json_files = glob.glob(os.path.join(DATA_DIR, "*.json"))
        
        if not json_files:
            return {"message": "No data processed by Spark yet.", "data": []}
        
        # Read and combine the data files into a pandas DataFrame
        df_list = [pd.read_json(f, lines=True) for f in json_files]
        combined_df = pd.concat(df_list, ignore_index=True)
        
        # Sort or grab the latest 10 records for the dashboard
        # (Tailoring it to return a clean JSON structure)
        latest_records = combined_df.tail(10).to_dict(orient="records")
        
        return {
            "total_records_processed": len(combined_df),
            "latest_data": latest_records
        }
        
    except Exception as e:
        return {"error": str(e)}

if __name__ == "__main__":
    import uvicorn
    # Runs the API server on port 8000
    uvicorn.run(app, host="127.0.0.1", port=8000)